import { PatientProfile, MembershipDetails, AuthUser, MedicationItem, MedicationDoseLog, WearableDevice, EmergencyContact, MetricThresholds } from '../types';
import { 
  INITIAL_VITALS, 
  INITIAL_THRESHOLDS, 
  PATIENT_LOCATIONS, 
  INITIAL_MEDICATIONS, 
  INITIAL_DOSE_LOGS, 
  INITIAL_DEVICES, 
  INITIAL_CONTACTS 
} from './mockData';

// Robert Miller (Patient 2 - Father, 81) specific prescriptions
export const ROBERT_MEDICATIONS: MedicationItem[] = [
  {
    id: 'med-carvedilol',
    name: 'Carvedilol',
    genericName: 'Carvedilol Tartrate',
    dosage: '12.5 mg',
    form: 'tablet',
    frequency: 'twice_daily',
    timingCategory: 'with_meals',
    scheduledTimes: ['08:30 AM', '08:30 PM'],
    prescribedFor: 'Post-CABG Heart Failure & Rate Control',
    prescribingDoctor: 'Dr. Marcus Vance (Cardiology)',
    rxNumber: 'RX-992144-C',
    pillsRemaining: 44,
    refillRemainingDays: 22,
    instructions: 'Take twice daily with breakfast and dinner. Do not skip abruptly.',
    colorTheme: 'blue',
    reminders: {
      enabled: true,
      reminderTimes: ['08:30 AM', '08:30 PM'],
      notificationChannels: {
        pushNotification: true,
        smsAlert: true,
        aiVoiceCallIfMissed: true,
        seniorSafeModeChime: true,
      },
      gracePeriodMinutes: 45,
    },
    vitalMetricCorrelation: 'heart_rate',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'med-furosemide',
    name: 'Furosemide',
    genericName: 'Lasix',
    dosage: '20 mg',
    form: 'tablet',
    frequency: 'once_daily',
    timingCategory: 'morning',
    scheduledTimes: ['09:00 AM'],
    prescribedFor: 'Peripheral Edema & Volume Control',
    prescribingDoctor: 'Dr. Marcus Vance (Cardiology)',
    rxNumber: 'RX-992145-F',
    pillsRemaining: 24,
    refillRemainingDays: 24,
    instructions: 'Take every morning. Avoid taking after 4:00 PM to prevent nocturnal sleep disruption.',
    colorTheme: 'teal',
    reminders: {
      enabled: true,
      reminderTimes: ['09:00 AM'],
      notificationChannels: {
        pushNotification: true,
        smsAlert: false,
        aiVoiceCallIfMissed: false,
        seniorSafeModeChime: true,
      },
      gracePeriodMinutes: 45,
    },
    vitalMetricCorrelation: 'blood_pressure',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'med-aspirin',
    name: 'Bayer Low Dose Aspirin',
    genericName: 'Aspirin EC',
    dosage: '81 mg',
    form: 'tablet',
    frequency: 'once_daily',
    timingCategory: 'afternoon',
    scheduledTimes: ['12:30 PM'],
    prescribedFor: 'Secondary Cardiac Thrombosis Prevention',
    prescribingDoctor: 'Dr. Marcus Vance (Cardiology)',
    rxNumber: 'RX-884210-A',
    pillsRemaining: 55,
    refillRemainingDays: 55,
    instructions: 'Take daily with lunch and full glass of water.',
    colorTheme: 'amber',
    reminders: {
      enabled: true,
      reminderTimes: ['12:30 PM'],
      notificationChannels: {
        pushNotification: true,
        smsAlert: false,
        aiVoiceCallIfMissed: false,
        seniorSafeModeChime: true,
      },
      gracePeriodMinutes: 45,
    },
    vitalMetricCorrelation: 'heart_rate',
    createdAt: '2026-09-01T08:00:00Z',
  },
];

export const ROBERT_DOSE_LOGS: MedicationDoseLog[] = [
  {
    id: 'rdose-1',
    medicationId: 'med-carvedilol',
    medicationName: 'Carvedilol',
    dosage: '12.5 mg',
    scheduledTime: '08:30 AM',
    scheduledDate: '2026-09-25',
    status: 'taken',
    loggedAt: '08:34 AM',
    loggedBy: 'patient',
  },
  {
    id: 'rdose-2',
    medicationId: 'med-furosemide',
    medicationName: 'Furosemide',
    dosage: '20 mg',
    scheduledTime: '09:00 AM',
    scheduledDate: '2026-09-25',
    status: 'taken',
    loggedAt: '09:02 AM',
    loggedBy: 'caregiver',
  },
  {
    id: 'rdose-3',
    medicationId: 'med-aspirin',
    medicationName: 'Bayer Low Dose Aspirin',
    dosage: '81 mg',
    scheduledTime: '12:30 PM',
    scheduledDate: '2026-09-25',
    status: 'taken',
    loggedAt: '12:35 PM',
    loggedBy: 'patient',
  },
  {
    id: 'rdose-4',
    medicationId: 'med-carvedilol',
    medicationName: 'Carvedilol',
    dosage: '12.5 mg',
    scheduledTime: '08:30 PM',
    scheduledDate: '2026-09-25',
    status: 'upcoming',
  },
];

export const ROBERT_DEVICES: WearableDevice[] = [
  {
    id: 'dev_garmin_venu',
    name: 'Garmin Venu 3 Pulse & Recovery',
    brand: 'Garmin',
    category: 'smartwatch',
    batteryPercent: 88,
    lastSync: '30s ago',
    connected: true,
    macAddress: 'C8:FD:19:92:4A:11',
    supportedMetrics: ['Heart Rate (BPM)', 'Continuous HRV', 'Pulse Ox SpO2', 'Body Battery'],
    telemetrySummary: 'Stable resting pulse 54 BPM. Zero arrhythmia triggers.',
  },
  {
    id: 'dev_withings_cuff',
    name: 'Withings BPM Core Wireless Cuff',
    brand: 'Withings',
    category: 'blood_pressure_cuff',
    batteryPercent: 92,
    lastSync: '1 hr ago',
    connected: true,
    macAddress: 'F2:18:7C:AA:01:99',
    supportedMetrics: ['Systolic / Diastolic BP', 'Pulse Transit Velocity', 'Single-Lead ECG'],
    telemetrySummary: 'Mean morning blood pressure 116/72 mmHg.',
  },
  {
    id: 'dev_medical_pendant',
    name: 'Philips Lifeline Medical Alert Pendant',
    brand: 'Philips',
    category: 'pendant_insole',
    batteryPercent: 96,
    lastSync: 'Live stream',
    connected: true,
    macAddress: '00:1E:C2:55:10:88',
    supportedMetrics: ['Fall Detection Accelerometer', 'Barometric Altitude Drop', 'SOS Button'],
    telemetrySummary: 'Wearer upright and ambulatory in living area.',
  },
];

export const ROBERT_THRESHOLDS: MetricThresholds = {
  heartRate: {
    minWarn: 44, // Adapted for Robert's Carvedilol rate control
    minCritical: 38,
    maxWarn: 92,
    maxCritical: 105,
    unit: 'BPM',
  },
  spo2: {
    minWarn: 92,
    minCritical: 88,
    unit: '%',
  },
  bloodPressureSystolic: {
    maxWarn: 135,
    maxCritical: 155,
    unit: 'mmHg',
  },
  bloodPressureDiastolic: {
    maxWarn: 85,
    maxCritical: 98,
    unit: 'mmHg',
  },
  bloodPressureMap: {
    minWarn: 65,
    maxWarn: 105,
    unit: 'mmHg',
  },
  respiratoryRate: {
    minWarn: 10,
    maxWarn: 22,
    minCritical: 8,
    maxCritical: 28,
    unit: 'breaths/min',
  },
  glucose: {
    urgentLow: 55,
    lowWarn: 70,
    highWarn: 140,
    severeHigh: 220,
    unit: 'mg/dL',
  },
  perfusionIndexMin: 0.5,
  thoracicBioimpedanceMinOhms: 35,
  coughRatePerHourMax: 8,
  skinTempDeviationMaxF: 2.2,
  fallDetectionEnabled: true,
  voiceTriageSequence: 'patient_then_caregiver_then_conference',
  wearableSyncProtocol: 'hybrid_bridge',
  activeClinicalTemplate: 'afib',
  adaptiveCircadianBaseline: true,
  activeEmsMode: 'certified_monitoring',
  gracePeriodSeconds: 25,
  voiceCallAutoDispatch: true,
};

export const ROBERT_CONTACTS: EmergencyContact[] = [
  {
    id: 'contact_david_r',
    name: 'David Miller',
    relation: 'Son (Primary Healthcare Proxy)',
    phone: '+1 (555) 234-8901',
    email: 'david.miller@kinotehealth.org',
    priorityOrder: 1,
    notifyOnWarning: true,
    notifyOnCritical: true,
    receiveAIVoiceCall: true,
  },
  {
    id: 'contact_sarah_r',
    name: 'Nurse Hannah Owens, RN',
    relation: 'Facility Charge Nurse',
    phone: '+1 (555) 662-9011',
    email: 'hannah.owens@stjude-senior.org',
    priorityOrder: 2,
    notifyOnWarning: false,
    notifyOnCritical: true,
    receiveAIVoiceCall: true,
  },
];

export const INITIAL_PATIENTS: PatientProfile[] = [
  {
    id: 'patient-eleanor',
    name: 'Eleanor Miller',
    relationship: 'Mother',
    age: 78,
    gender: 'Female',
    roomOrUnit: 'Main Residence - Master Suite',
    primaryCondition: 'Essential Hypertension & Type 2 Diabetes (CGM Monitored)',
    avatarBg: 'from-teal-600 to-emerald-700',
    location: PATIENT_LOCATIONS[0],
    vitals: INITIAL_VITALS,
    thresholds: INITIAL_THRESHOLDS,
    medications: INITIAL_MEDICATIONS,
    doseLogs: INITIAL_DOSE_LOGS,
    devices: INITIAL_DEVICES,
    emergencyContacts: INITIAL_CONTACTS,
  },
  {
    id: 'patient-robert',
    name: 'Robert Miller',
    relationship: 'Father',
    age: 81,
    gender: 'Male',
    roomOrUnit: 'St. Jude Assisted Living - Suite 4B',
    primaryCondition: 'Sinus Bradycardia (Baseline 48-56 BPM) & Post-CABG Recovery',
    avatarBg: 'from-blue-600 to-indigo-800',
    location: {
      label: 'St. Jude Senior Living (Suite 4B)',
      address: '1420 Mission Blvd, Suite 4B, Springfield, IL 62701',
      coordinates: { lat: 39.7712, lng: -89.6543 },
      nearestPSAP: 'Springfield Metro Central Fire & Rescue #4',
      dispatchPreference: 'certified_monitoring',
    },
    vitals: {
      heartRate: 54, // Baseline bradycardic
      spo2: 96,
      bloodPressureSystolic: 116,
      bloodPressureDiastolic: 72,
      respiratoryRate: 15,
      temperature: 98.4,
      glucose: 98,
      fallDetected: false,
      timestamp: 'Just now',
    },
    thresholds: ROBERT_THRESHOLDS,
    medications: ROBERT_MEDICATIONS,
    doseLogs: ROBERT_DOSE_LOGS,
    devices: ROBERT_DEVICES,
    emergencyContacts: ROBERT_CONTACTS,
  },
];

export const INITIAL_MEMBERSHIP: MembershipDetails = {
  planType: 'caregiver_plus',
  planName: 'KINOTE Caregiver Plus',
  status: 'active',
  renewalDate: 'October 25, 2026',
  daysRemaining: 30,
  billingCycle: 'monthly',
  priceFormatted: '$29 / month',
  maxSeniors: 3,
  currentSeniorsCount: 2, // Eleanor & Robert
  features: {
    aiVoiceMinutesTotal: 120,
    aiVoiceMinutesUsed: 38,
    cellularEsimActive: true,
    rechartsAnalytics30Day: true,
    multiCaregiverSharing: true,
    emsDirectBridge247: true,
    unlimitedWearablesSync: true,
  },
  paymentMethod: {
    brand: 'visa',
    last4: '4242',
    expMonth: 9,
    expYear: 2028,
  },
  invoices: [
    {
      id: 'inv_2026_09',
      date: 'Sep 25, 2026',
      amount: '$29.00',
      status: 'paid',
    },
    {
      id: 'inv_2026_08',
      date: 'Aug 25, 2026',
      amount: '$29.00',
      status: 'paid',
    },
    {
      id: 'inv_2026_07',
      date: 'Jul 25, 2026',
      amount: '$29.00',
      status: 'paid',
    },
  ],
};

export const DEMO_USERS: AuthUser[] = [
  {
    id: 'user_david_miller',
    name: 'David Miller',
    email: 'david.miller@kinotehealth.org',
    phone: '+1 (555) 234-8901',
    role: 'family_caregiver',
    authMethod: 'biometric',
    lastLogin: 'Today, 09:15 AM',
  },
  {
    id: 'user_eleanor_miller',
    name: 'Eleanor Miller',
    email: 'eleanor.miller@kinotehealth.org',
    phone: '+1 (555) 321-7788',
    role: 'senior_patient',
    authMethod: 'senior_pin',
    lastLogin: 'Today, 08:30 AM',
  },
  {
    id: 'user_robert_miller',
    name: 'Robert Miller',
    email: 'robert.miller@kinotehealth.org',
    phone: '+1 (555) 772-4411',
    role: 'senior_patient',
    authMethod: 'senior_pin',
    lastLogin: 'Today, 07:45 AM',
  },
  {
    id: 'user_dr_thorne',
    name: 'Dr. Aris Thorne, MD',
    email: 'dr.thorne@mercycardiac.org',
    phone: '+1 (555) 441-9922',
    role: 'attending_physician',
    authMethod: 'email',
    lastLogin: 'Yesterday, 04:45 PM',
  },
];
