import {
  AuditLogEntry,
  EmergencyContact,
  MetricThresholds,
  PatientLocation,
  VitalsReading,
  WearableDevice,
  WearableCategory,
  AIVoiceCallLog,
  AIChatMessage,
  HistoricalVitalDay,
  HistoricalIntradayReading,
  MedicationItem,
  MedicationDoseLog,
  MedicationAdherenceSummary,
} from '../types';

export const INITIAL_THRESHOLDS: MetricThresholds = {
  heartRate: {
    minWarn: 50,
    maxWarn: 100,
    minCritical: 42,
    maxCritical: 130,
    unit: 'BPM',
  },
  bloodPressureSystolic: {
    maxWarn: 135,
    maxCritical: 175,
    unit: 'mmHg',
  },
  bloodPressureDiastolic: {
    maxWarn: 88,
    maxCritical: 105,
    unit: 'mmHg',
  },
  bloodPressureMap: {
    minWarn: 70,
    maxWarn: 105,
    unit: 'mmHg',
  },
  spo2: {
    minWarn: 93,
    minCritical: 88,
    unit: '%',
  },
  respiratoryRate: {
    minWarn: 12,
    maxWarn: 22,
    minCritical: 8,
    maxCritical: 28,
    unit: 'breaths/min',
  },
  glucose: {
    urgentLow: 54,
    lowWarn: 70,
    highWarn: 180,
    severeHigh: 250,
    unit: 'mg/dL',
  },
  perfusionIndexMin: 1.0,
  thoracicBioimpedanceMinOhms: 32.0,
  coughRatePerHourMax: 6,
  skinTempDeviationMaxF: 2.2,
  fallDetectionEnabled: true,
  gracePeriodSeconds: 20,
  voiceCallAutoDispatch: true,
  voiceTriageSequence: 'patient_then_caregiver_then_conference',
  wearableSyncProtocol: 'hybrid_bridge',
  activeClinicalTemplate: 'standard',
  adaptiveCircadianBaseline: true,
  activeEmsMode: 'certified_monitoring',
};

export const PATIENT_LOCATIONS: PatientLocation[] = [
  {
    label: 'Primary Residence (Oakwood Home)',
    address: '742 Evergreen Terrace, Springfield, IL 62704',
    coordinates: { lat: 39.7817, lng: -89.6501 },
    nearestPSAP: 'Sangamon County Regional 911 Dispatch',
    dispatchPreference: 'certified_monitoring',
  },
  {
    label: 'Visiting Sibling / Traveling',
    address: '1420 Lake Shore Drive, Apt 11B, Chicago, IL 60610',
    coordinates: { lat: 41.9088, lng: -87.6253 },
    nearestPSAP: 'Chicago OEMC Public Safety PSAP #1',
    dispatchPreference: 'caregiver_guided',
  },
  {
    label: 'Summer Lake Cottage (Rural)',
    address: 'Route 9 Mile 44, Eagle River, WI 54521',
    coordinates: { lat: 45.9172, lng: -89.2443 },
    nearestPSAP: 'Vilas County Sheriff E911 Emergency Center',
    dispatchPreference: 'direct_psap',
  },
];

export const INITIAL_VITALS: VitalsReading = {
  timestamp: 'Just now',
  heartRate: 72,
  bloodPressureSystolic: 122,
  bloodPressureDiastolic: 78,
  spo2: 98,
  respiratoryRate: 16,
  glucose: 104,
  temperature: 98.4,
  fallDetected: false,
  smartwatch: {
    ecgRhythm: 'normal_sinus',
    restingHeartRate: 68,
    walkingHeartRateAvg: 94,
    hrvRmssd: 38,
    wristTempDeviation: 0.1,
    cEdaStressEvents: 1,
    walkingSteadiness: 'ok',
    dailySteps: 4120,
    sleepEfficiencyPercent: 86,
  },
  smartRing: {
    fingerPpgHeartRate: 71,
    nocturnalHrv: 44,
    skinTemperatureCelsius: 36.6,
    skinTempDeviation: 0.2,
    sleepReadinessScore: 88,
    breathingDisturbancesPerHour: 1.2,
    deepSleepPercent: 19,
    remSleepPercent: 22,
    circadianAlignment: 'optimal',
  },
  bpCuff: {
    systolic: 122,
    diastolic: 78,
    meanArterialPressure: 92.7,
    pulsePressure: 44,
    cuffPulseRate: 72,
    irregularHeartbeatDetected: false,
    cuffFitStatus: 'proper_fit',
    valvularMurmurDetected: false,
  },
  cgm: {
    currentGlucose: 104,
    trendArrow: 'steady',
    timeInRangePercent: 94,
    timeBelowRangePercent: 1,
    timeAboveRangePercent: 5,
    glucoseManagementIndicator: 5.8,
    sensorDaysRemaining: 8,
    urgentLowPredictiveWarning: false,
  },
  medicalPatch: {
    continuous3LeadEcg: 'sinus',
    pvcCountPerHour: 2,
    thoracicBioimpedanceOhms: 48.2,
    fluidRetentionStatus: 'nominal',
    coughFrequencyPerHour: 1,
    coreBodyTemperature: 98.4,
    posturalTiltDegrees: 12,
    bedboundHoursToday: 6.8,
  },
  pulseOx: {
    continuousSpo2: 98,
    oxygenDesaturationIndex: 0.8,
    perfusionIndexPercent: 4.6,
    plethWaveformQuality: 'optimal',
    hypoxicEventsLogged: 0,
    hapticAlarmTriggered: false,
  },
  smartScale: {
    weightLbs: 148.6,
    bmi: 23.4,
    sixLeadEcg: 'normal',
    pulseWaveVelocityMps: 7.2,
    vascularAgeYears: 66,
    sudomotorNerveScore: 84,
    visceralFatRating: 5,
    extracellularWaterRatio: 38.8,
    skeletalMuscleMassLbs: 58.2,
  },
  pendantInsole: {
    barometricAltitudeDropMeters: 0,
    impactShockForceG: 0.12,
    postImpactImmobilitySeconds: 0,
    plantarPressureBalancePercent: { left: 51, right: 49 },
    cadenceStepsPerMin: 88,
    freezeOfGaitEvents: 0,
    sosButtonPressed: false,
    gpsCoordinates: { lat: 39.7817, lng: -89.6501, accuracyMeters: 4.2 },
  },
};

export const INITIAL_DEVICES: WearableDevice[] = [
  {
    id: 'dev_apple_watch',
    name: 'Apple Watch Series 10',
    brand: 'Apple HealthKit',
    category: 'smartwatch',
    batteryPercent: 88,
    lastSync: '10 seconds ago',
    connected: true,
    macAddress: 'C4:B3:01:E2:4A:99',
    telemetrySummary: 'Single-lead ECG (Sinus), SpO2 98%, HR 72 BPM, Walking Steadiness: Good',
    supportedMetrics: [
      'Continuous Heart Rate',
      'Single-Lead ECG / AFib',
      'Blood Oxygen (SpO2)',
      'Wrist Temperature Baseline',
      'Fall & Hard Impact Detection',
      'Walking Steadiness & Asymmetry',
      'Sleep Stages (REM, Deep, Core)',
    ],
    metricsSpecs: [
      { name: 'ECG Rhythm', unit: 'rhythm', samplingInterval: 'On-demand & background', clinicalPurpose: 'Early detection of Atrial Fibrillation and cardiac arrhythmias', lastValue: 'Normal Sinus', status: 'nominal' },
      { name: 'Resting Heart Rate', unit: 'BPM', samplingInterval: 'Continuous (every 5s)', clinicalPurpose: 'Autonomic nervous baseline & cardiac workload tracking', lastValue: '68 BPM', status: 'nominal' },
      { name: 'Blood Oxygen (SpO2)', unit: '%', samplingInterval: 'Background spot checks', clinicalPurpose: 'Detects silent hypoxia & nocturnal desaturations', lastValue: '98%', status: 'nominal' },
      { name: 'Wrist Temp Deviation', unit: '°F', samplingInterval: 'Every 5s during sleep', clinicalPurpose: 'Circadian phase and early infection/fever biomarker', lastValue: '+0.1°F', status: 'nominal' },
      { name: 'Walking Steadiness', unit: 'gait score', samplingInterval: 'Passive mobility sensing', clinicalPurpose: 'Predictive elderly fall risk stratification', lastValue: 'Optimal', status: 'nominal' },
    ],
  },
  {
    id: 'dev_oura_ring',
    name: 'Oura Ring Gen 3 Horizon',
    brand: 'Oura Health Cloud',
    category: 'ring',
    batteryPercent: 92,
    lastSync: '1 minute ago',
    connected: true,
    macAddress: '78:F0:11:AA:67:CC',
    telemetrySummary: 'Nocturnal HRV 44ms, Skin Temp +0.2°C, Sleep Readiness 88/100, BDI 1.2/hr',
    supportedMetrics: [
      'Finger Artery PPG Pulse',
      'Continuous Nocturnal HRV (rMSSD)',
      'High-Precision NTC Skin Temperature (±0.05°C)',
      'Sleep Recovery & Readiness Index',
      'Breathing Disturbances Index (BDI)',
      'Circadian Alignment Tracking',
    ],
    metricsSpecs: [
      { name: 'Nocturnal HRV', unit: 'ms', samplingInterval: 'Every 5 mins during sleep', clinicalPurpose: 'Sympathetic vs parasympathetic nervous recovery & chronic stress', lastValue: '44 ms', status: 'nominal' },
      { name: 'Skin Temperature', unit: '°C offset', samplingInterval: 'Continuous 1-minute resolution', clinicalPurpose: 'Immunological trigger detection, fever warning & circadian tracking', lastValue: '+0.2°C', status: 'nominal' },
      { name: 'Breathing Disturbances', unit: 'events/hr', samplingInterval: 'Overnight continuous', clinicalPurpose: 'Screening for obstructive sleep apnea (OSA)', lastValue: '1.2/hr (Normal)', status: 'nominal' },
      { name: 'Sleep Readiness Score', unit: 'score 0-100', samplingInterval: 'Computed daily at wake', clinicalPurpose: 'Physiological vitality & physical stamina reserve', lastValue: '88/100', status: 'nominal' },
    ],
  },
  {
    id: 'dev_omron_bp',
    name: 'Omron Evolv Upper Arm Cuff',
    brand: 'Omron Healthcare',
    category: 'blood_pressure_cuff',
    batteryPercent: 74,
    lastSync: '15 minutes ago',
    connected: true,
    macAddress: '1A:89:BC:33:02:11',
    telemetrySummary: 'BP 122/78 mmHg, MAP 92.7 mmHg, Pulse Pressure 44 mmHg, Arrhythmia: Negative',
    supportedMetrics: [
      'Systolic Blood Pressure',
      'Diastolic Blood Pressure',
      'Mean Arterial Pressure (MAP)',
      'Pulse Pressure (Arterial Stiffness)',
      'Cuff Inflation Pulse Rate',
      'Irregular Heartbeat (IHB) Alert',
    ],
    metricsSpecs: [
      { name: 'Systolic Blood Pressure', unit: 'mmHg', samplingInterval: 'Daily / post-medication', clinicalPurpose: 'Stroke and hypertensive crisis surveillance', lastValue: '122 mmHg', status: 'nominal' },
      { name: 'Diastolic Blood Pressure', unit: 'mmHg', samplingInterval: 'Daily / post-medication', clinicalPurpose: 'Coronary perfusion and vascular resistance monitoring', lastValue: '78 mmHg', status: 'nominal' },
      { name: 'Mean Arterial Pressure (MAP)', unit: 'mmHg', samplingInterval: 'Calculated per reading', clinicalPurpose: 'Vital organ perfusion pressure (Normal: 70–105 mmHg)', lastValue: '92.7 mmHg', status: 'nominal' },
      { name: 'Pulse Pressure', unit: 'mmHg', samplingInterval: 'Calculated (SBP - DBP)', clinicalPurpose: 'Marker of aortic stiffness and cardiovascular risk', lastValue: '44 mmHg', status: 'nominal' },
      { name: 'Irregular Heartbeat (IHB)', unit: 'flag', samplingInterval: 'During inflation', clinicalPurpose: 'Flags premature ventricular contractions or atrial fibrillation', lastValue: 'None detected', status: 'nominal' },
    ],
  },
  {
    id: 'dev_dexcom_cgm',
    name: 'Dexcom G7 Continuous Glucose',
    brand: 'Dexcom CGM Direct',
    category: 'cgm_patch',
    batteryPercent: 100,
    lastSync: '2 minutes ago',
    connected: true,
    macAddress: '5C:19:D8:03:EE:41',
    telemetrySummary: 'Glucose 104 mg/dL (Steady arrow), TIR 94%, GMI 5.8%, Urgent Low Alarm Armed',
    supportedMetrics: [
      'Interstitial Glucose Level (mg/dL)',
      'Rate-of-Change Trend Vectors (↑↑, ↑, →, ↓, ↓↓)',
      'Time in Range (TIR %)',
      'Time Below Range (TBR % Hypoglycemia Risk)',
      'Time Above Range (TAR % Hyperglycemia Risk)',
      'Glucose Management Indicator (GMI / est. HbA1c)',
      'Sensor Days Remaining & Filament Health',
    ],
    metricsSpecs: [
      { name: 'Current Glucose', unit: 'mg/dL', samplingInterval: 'Continuous (every 5 mins)', clinicalPurpose: 'Prevents acute hypoglycemic confusion, seizures, or diabetic coma', lastValue: '104 mg/dL (Steady →)', status: 'nominal' },
      { name: 'Time in Range (TIR)', unit: '%', samplingInterval: 'Continuous 24-hr rolling', clinicalPurpose: 'Clinical gold standard for glycemic stability (Target >70%)', lastValue: '94%', status: 'nominal' },
      { name: 'Time Below Range (TBR)', unit: '%', samplingInterval: 'Continuous 24-hr rolling', clinicalPurpose: 'Hypoglycemia safety metric (Target <4%, Urgent Low <1%)', lastValue: '1%', status: 'nominal' },
      { name: 'Estimated HbA1c (GMI)', unit: '%', samplingInterval: 'Calculated 14-day mean', clinicalPurpose: 'Long-term glycemic hemoglobin glycosylation index', lastValue: '5.8%', status: 'nominal' },
    ],
  },
  {
    id: 'dev_biobutton_patch',
    name: 'BioIntelliSense BioButton Medical Patch',
    brand: 'BioIntelliSense Clinical',
    category: 'medical_patch',
    batteryPercent: 82,
    lastSync: '5 minutes ago',
    connected: true,
    macAddress: '7A:41:99:BC:11:04',
    telemetrySummary: 'Continuous 3-Lead ECG, Thoracic Bioimpedance 48.2Ω (No Edema), Cough: 1/hr',
    supportedMetrics: [
      'Continuous 3-Lead ECG Rhythm Strip',
      'Premature Ventricular Contractions (PVC) Hourly Count',
      'Thoracic Bioimpedance (Pulmonary Edema / CHF Fluid)',
      'Acoustic Cough & Sneeze Frequency',
      'Continuous High-Res Respiration Rate',
      'Postural Upright vs Bedbound Angle',
    ],
    metricsSpecs: [
      { name: 'Thoracic Bioimpedance', unit: 'Ohms (Ω)', samplingInterval: 'Continuous (hourly average)', clinicalPurpose: 'Early warning of Congestive Heart Failure lung fluid accumulation', lastValue: '48.2 Ω (Nominal)', status: 'nominal' },
      { name: 'Cough Frequency', unit: 'coughs/hour', samplingInterval: 'Continuous acoustic sensing', clinicalPurpose: 'Early bio-marker of pneumonia, COPD flare-up, or viral infection', lastValue: '1 / hour', status: 'nominal' },
      { name: 'PVC Arrhythmia Burden', unit: 'events/hr', samplingInterval: 'Continuous ECG analysis', clinicalPurpose: 'Ventricular ectopy count alerting to myocardial ischemia', lastValue: '2 / hour', status: 'nominal' },
      { name: 'Upright Posture Time', unit: 'hours', samplingInterval: 'Continuous inclinometer', clinicalPurpose: 'Monitors senior mobility and prevents bedridden complications', lastValue: '6.8 hours', status: 'nominal' },
    ],
  },
  {
    id: 'dev_masimo_pulseox',
    name: 'Masimo MightySat Continuous Pulse Ox',
    brand: 'Masimo Medical BLE',
    category: 'pulse_oximeter',
    batteryPercent: 91,
    lastSync: '20 seconds ago',
    connected: true,
    macAddress: '11:22:33:44:55:66',
    telemetrySummary: 'SpO2 98%, Perfusion Index 4.6%, ODI 0.8 dips/hr, Plethysmograph: Optimal',
    supportedMetrics: [
      'Continuous SpO2 (1-Second High Resolution)',
      'Perfusion Index (PI % Peripheral Blood Flow)',
      'Oxygen Desaturation Index (ODI 4% Dips)',
      'Plethysmographic Waveform Quality Index',
      'Continuous Pulse Rate & Haptic Vibrate Alarm',
    ],
    metricsSpecs: [
      { name: 'High-Res SpO2', unit: '%', samplingInterval: '1-second continuous', clinicalPurpose: 'Clinical-grade oxygen saturation with motion tolerance', lastValue: '98%', status: 'nominal' },
      { name: 'Perfusion Index (PI)', unit: '%', samplingInterval: '1-second continuous', clinicalPurpose: 'Indicates peripheral arterial pulse strength & hypothermia risk', lastValue: '4.6%', status: 'nominal' },
      { name: 'Oxygen Desaturation Index', unit: 'dips/hr', samplingInterval: 'Continuous rolling hourly', clinicalPurpose: 'Quantifies frequency of 4%+ oxygen saturation drops', lastValue: '0.8 dips/hr', status: 'nominal' },
    ],
  },
  {
    id: 'dev_withings_scale',
    name: 'Withings Body Scan Medical Station',
    brand: 'Withings Health Solutions',
    category: 'smart_scale',
    batteryPercent: 78,
    lastSync: 'Today at 07:30 AM',
    connected: true,
    macAddress: '88:77:66:55:44:33',
    telemetrySummary: 'Weight 148.6 lbs, PWV 7.2 m/s (Vascular Age 66y), 6-Lead ECG: Normal, Nerve Score: 84',
    supportedMetrics: [
      'Body Weight & BMI',
      '6-Lead Segmental ECG (Leads I, II, III, aVR, aVL, aVF)',
      'Pulse Wave Velocity (PWV m/s Arterial Stiffness)',
      'Vascular Age Assessment',
      'Sudomotor Nerve Health (Electrochemical Conductance)',
      'Segmental Body Composition & Visceral Fat',
      'Extracellular Water Ratio (Peripheral Edema)',
    ],
    metricsSpecs: [
      { name: 'Pulse Wave Velocity (PWV)', unit: 'm/s', samplingInterval: 'Every morning weigh-in', clinicalPurpose: 'Arterial wall stiffness & vascular age evaluation', lastValue: '7.2 m/s', status: 'nominal' },
      { name: 'Vascular Age', unit: 'years', samplingInterval: 'Computed vs age norm', clinicalPurpose: 'Direct cardio-vascular health index', lastValue: '66 yrs (Optimal)', status: 'nominal' },
      { name: 'Sudomotor Nerve Score', unit: 'ESC score (0-100)', samplingInterval: 'Every morning weigh-in', clinicalPurpose: 'Detects autonomic & diabetic peripheral neuropathy in feet', lastValue: '84 (Healthy)', status: 'nominal' },
      { name: 'Extracellular Water %', unit: '% of body weight', samplingInterval: 'BIA multi-frequency', clinicalPurpose: 'Early detection of bilateral ankle/leg edema & fluid overload', lastValue: '38.8%', status: 'nominal' },
    ],
  },
  {
    id: 'dev_guardian_pendant',
    name: 'Medical Guardian MGMini Smart SOS & Insole',
    brand: 'Medical Guardian / Sensoria',
    category: 'pendant_insole',
    batteryPercent: 85,
    lastSync: '3 minutes ago',
    connected: true,
    macAddress: '99:88:77:66:55:44',
    telemetrySummary: 'Altimeter: Normal, Impact Shock: 0.12G, Plantar Balance: 51%/49%, GPS: Fix OK',
    supportedMetrics: [
      'Barometric Altimeter Rapid Descent (>1.2m drop)',
      'High-G Multi-Axis Impact Shock Vector (>4.5G)',
      'Post-Fall Immobility Timer',
      'Dynamic Plantar Foot Pressure Balance (%)',
      'Freeze-of-Gait (FOG Parkinsonian Shuffling)',
      'Physical SOS Duplex Voice Button',
      'Dual-Band GPS & WiFi Indoor Beaconing',
    ],
    metricsSpecs: [
      { name: 'Barometric Altitude Change', unit: 'meters', samplingInterval: 'Continuous 10Hz baro', clinicalPurpose: 'Detects true freefall prior to ground collision', lastValue: '0.0 m (Stable)', status: 'nominal' },
      { name: 'Impact Shock Force', unit: 'G-force', samplingInterval: '100Hz shock sensor', clinicalPurpose: 'Validates traumatic fall severity and head impact probability', lastValue: '0.12 G', status: 'nominal' },
      { name: 'Plantar Pressure Balance', unit: '% Left / Right', samplingInterval: 'Dynamic pressure grid', clinicalPurpose: 'Monitors stroke hemiparesis or asymmetrical limp', lastValue: '51% L / 49% R', status: 'nominal' },
      { name: 'Emergency SOS Button', unit: 'state', samplingInterval: 'Instant hardware interrupt', clinicalPurpose: 'One-touch physical voice link for senior parent', lastValue: 'Armed / Ready', status: 'nominal' },
    ],
  },
];

export interface WearableCategoryDefinition {
  id: WearableCategory;
  title: string;
  subtitle: string;
  iconName: string;
  description: string;
  typicalBrands: string[];
  collectedDataPoints: {
    name: string;
    clinicalValue: string;
    frequency: string;
    actionableAlert: string;
  }[];
}

export const WEARABLE_DATA_DICTIONARY: WearableCategoryDefinition[] = [
  {
    id: 'smartwatch',
    title: 'Smartwatches & Advanced Fitness Trackers',
    subtitle: 'Continuous Wrist Photoplethysmography, ECG & Kinematic Sensors',
    iconName: 'Watch',
    description: 'High-frequency wrist-worn devices that continuously stream cardiovascular, respiratory, thermal, and mobility data.',
    typicalBrands: ['Apple Watch Series / Ultra', 'Samsung Galaxy Watch', 'Garmin Venu / Forerunner', 'Fitbit Sense 2', 'Google Pixel Watch'],
    collectedDataPoints: [
      { name: 'Continuous & Resting Heart Rate', clinicalValue: 'Cardiovascular baseline workload, resting tachycardia or severe bradycardia alerting', frequency: 'Continuous (every 1-5 sec)', actionableAlert: 'Triggers emergency voice check when HR > maxWarn or < minWarn' },
      { name: 'Single-Lead ECG (Lead I)', clinicalValue: 'Clinical rhythm strip detecting Atrial Fibrillation (AFib), premature contractions, and sinus rhythms', frequency: 'On-demand & passive irregular rhythm detection', actionableAlert: 'Automatic notification to caregiver & cardiologist on AFib confirmation' },
      { name: 'Blood Oxygen Saturation (SpO2)', clinicalValue: 'Reflection photoplethysmography detecting daytime hypoxia and nocturnal hypoxic burden', frequency: 'Periodic spot checks & continuous during sleep', actionableAlert: 'Hypoxia warning when SpO2 < 93%, critical emergency below 88%' },
      { name: 'Wrist Temperature Variation', clinicalValue: 'Tracks circadian temperature oscillations against baseline to flag infection or fever', frequency: 'Overnight continuous', actionableAlert: 'Fever alert when temp deviation exceeds +2.0°F above 7-day baseline' },
      { name: 'Electrodermal Activity (cEDA / EDA)', clinicalValue: 'Micro-sweat galvanic skin response quantifying autonomic sympathetic nervous stress', frequency: 'Continuous skin conductance', actionableAlert: 'Stress spike alert with calming voice prompt to senior' },
      { name: 'Tri-Axial Fall & Hard Impact Detection', clinicalValue: 'Combines sudden accelerometer deceleration with gyroscope rotation and post-impact silence', frequency: 'Continuous 100Hz sampling', actionableAlert: 'Immediate 20s grace period countdown followed by AI Emergency Voice Call' },
      { name: 'Walking Steadiness & Gait Asymmetry', clinicalValue: 'Analyzes step time symmetry, double support time, and walking speed to stratify 12-month fall risk', frequency: 'Passive daily walking sessions', actionableAlert: 'Caregiver notification if walking steadiness drops into "Very Low" category' },
      { name: 'Sleep Architecture (REM, Deep, Core, Awake)', clinicalValue: 'Restorative sleep staging to detect fragmented sleep, insomnia, or cognitive fatigue', frequency: 'Nocturnal multi-sensor fusion', actionableAlert: 'Daily summary insight with restorative sleep score' },
    ],
  },
  {
    id: 'ring',
    title: 'Smart Health Rings',
    subtitle: 'Finger Artery PPG & Ultra-Sensitive Thermal Sensors',
    iconName: 'CircleDot',
    description: 'Minimalist unobtrusive finger rings that capture high-fidelity arterial blood flow metrics due to the proximity of digital palmar arteries.',
    typicalBrands: ['Oura Ring Gen 3 / Gen 4', 'Ultrahuman Ring AIR', 'RingConn Gen 2', 'Samsung Galaxy Ring'],
    collectedDataPoints: [
      { name: 'Finger Artery Resting Heart Rate', clinicalValue: 'Arterial PPG with higher signal-to-noise ratio than wrist devices', frequency: 'Continuous overnight (every 1 min)', actionableAlert: 'Elevated resting HR indicating impending infection or dehydration' },
      { name: 'Continuous Nocturnal HRV (rMSSD)', clinicalValue: 'Heart Rate Variability reflecting parasympathetic tone and autonomic resilience', frequency: 'Sampled every 5 minutes during sleep', actionableAlert: 'Flagged when 3-day rolling HRV drops >25% below baseline' },
      { name: 'Negative Temperature Coefficient (NTC) Skin Temp', clinicalValue: 'Direct digital capillary temperature calibrated to 0.05°C precision', frequency: 'Continuous minute-by-minute', actionableAlert: 'Early illness detection up to 48 hours prior to subjective fever' },
      { name: 'Breathing Disturbance Index (BDI)', clinicalValue: 'Quantifies nocturnal oxygen dips and respiratory flow disruptions', frequency: 'Continuous overnight', actionableAlert: 'Sleep apnea risk score warning to adult child' },
      { name: 'Sleep Readiness & Recovery Score', clinicalValue: 'Composite index of previous day exertion, nocturnal resting heart rate, and sleep staging', frequency: 'Calculated daily upon wake', actionableAlert: 'Included in morning Kinote AI Assistant briefing' },
    ],
  },
  {
    id: 'blood_pressure_cuff',
    title: 'Wireless Medical Blood Pressure Monitors',
    subtitle: 'Oscillometric & Digital Acoustic Arterial Pressure Measurement',
    iconName: 'Activity',
    description: 'Upper arm and wrist oscillometric cuffs that provide clinical-grade blood pressure, mean arterial pressure, and irregular pulse detection.',
    typicalBrands: ['Omron Evolv / Complete', 'Withings BPM Core / BPM Connect', 'Welch Allyn Home BP', 'A&D Medical Wireless'],
    collectedDataPoints: [
      { name: 'Systolic Blood Pressure (SBP)', clinicalValue: 'Peak arterial pressure during cardiac contraction; primary risk factor for stroke and aneurysm', frequency: 'Scheduled morning/evening measurements', actionableAlert: 'Immediate push notification if SBP > 135 mmHg (warn) or > 175 mmHg (critical)' },
      { name: 'Diastolic Blood Pressure (DBP)', clinicalValue: 'Minimum arterial pressure during cardiac relaxation; indicates peripheral vascular resistance', frequency: 'Per measurement', actionableAlert: 'Alert when DBP > 88 mmHg (warn) or > 105 mmHg (critical)' },
      { name: 'Mean Arterial Pressure (MAP)', clinicalValue: 'Average arterial perfusion pressure: (2*DBP + SBP)/3; vital organ perfusion marker', frequency: 'Calculated instantly', actionableAlert: 'Flagged if MAP falls below 70 mmHg (hypoperfusion risk) or > 105 mmHg' },
      { name: 'Pulse Pressure (SBP - DBP)', clinicalValue: 'Difference between systolic and diastolic pressure; indicator of large artery stiffness', frequency: 'Calculated instantly', actionableAlert: 'Alert if pulse pressure exceeds 60 mmHg (elevated vascular risk)' },
      { name: 'Irregular Heartbeat (IHB) Sensor', clinicalValue: 'Analyzes pulse rhythm intervals during cuff deflation to detect ectopic beats or AFib', frequency: 'During every reading', actionableAlert: 'Arrhythmia icon logged and forwarded to attending cardiologist' },
      { name: 'Integrated Digital Stethoscope Phonocardiogram', clinicalValue: 'Acoustic sensor on cuff (Withings BPM Core) detecting aortic/mitral valve murmurs', frequency: 'During cardiac cuff cycle', actionableAlert: 'Valvular anomaly flag alerting to aortic stenosis risk' },
    ],
  },
  {
    id: 'cgm_patch',
    title: 'Continuous Glucose Monitors (CGM)',
    subtitle: 'Interstitial Fluid Enzymatic Biosensors with Real-Time Telemetry',
    iconName: 'Droplet',
    description: 'Subcutaneous filament patches that measure interstitial glucose levels continuously to prevent acute hypoglycemia and severe hyperglycemia.',
    typicalBrands: ['Dexcom G7 / ONE+', 'Abbott FreeStyle Libre 3', 'Medtronic Guardian 4', 'Senseonics Eversense'],
    collectedDataPoints: [
      { name: 'Real-Time Interstitial Glucose', clinicalValue: 'Direct glucose concentration in subcutaneous tissue, updating every 1 to 5 minutes', frequency: 'Continuous (every 1-5 min)', actionableAlert: 'Immediate critical alarm if glucose < 54 mg/dL (urgent low) or > 250 mg/dL' },
      { name: 'Rate-of-Change Trend Vectors (↑↑, ↑, →, ↓, ↓↓)', clinicalValue: 'Velocity of glucose change indicating whether blood sugar is dropping rapidly (>2 mg/dL/min)', frequency: 'Every 5 minutes', actionableAlert: 'Predictive alert 20 minutes before hypoglycemia onset' },
      { name: 'Time in Range (TIR % - 70-180 mg/dL)', clinicalValue: 'Gold standard diabetes quality-of-life metric; correlates directly with microvascular protection', frequency: 'Continuous 24-hr rolling', actionableAlert: 'Daily summary reports TIR percentage to adult child' },
      { name: 'Time Below Range (TBR % < 70 mg/dL)', clinicalValue: 'Tracks cumulative hypoglycemic exposure, which causes senior confusion, falls, and cardiac events', frequency: 'Continuous', actionableAlert: 'Caregiver push alert upon any TBR event' },
      { name: 'Glucose Management Indicator (GMI %)', clinicalValue: 'Estimated laboratory HbA1c based on 14-day continuous mean glucose data', frequency: 'Calculated weekly', actionableAlert: 'Logged in physician report' },
      { name: 'Sensor Life & Insertion Site Health', clinicalValue: 'Countdown of remaining sensor days (typically 10-14 days) and calibration status', frequency: 'Daily hardware check', actionableAlert: 'Reminder to adult child 48 hours before sensor expiration' },
    ],
  },
  {
    id: 'medical_patch',
    title: 'Clinical Medical Chest Patches & Holters',
    subtitle: 'Multi-Vector Continuous ECG, Bioimpedance & Acoustic Sensors',
    iconName: 'HeartHandshake',
    description: 'Adhesive medical chest monitors that capture continuous multi-lead ECG, acoustic cough frequency, and thoracic fluid bioimpedance.',
    typicalBrands: ['BioIntelliSense BioButton', 'VivaLNK Vital Scout', 'iRhythm Zio Patch', 'Philips BioTel Heart'],
    collectedDataPoints: [
      { name: 'Continuous Multi-Lead ECG', clinicalValue: 'Uninterrupted clinical-grade electrocardiogram recording every heartbeat for up to 30 days', frequency: 'Continuous 250Hz recording', actionableAlert: 'Cardiology escalation on sustained tachyarrhythmia or ventricular pauses' },
      { name: 'Thoracic Bioimpedance (Lung Fluid Index)', clinicalValue: 'Measures chest electrical impedance; decreasing resistance indicates pulmonary fluid accumulation', frequency: 'Hourly average continuous', actionableAlert: 'Critical early decompensation alert for Congestive Heart Failure (CHF)' },
      { name: 'Acoustic Cough & Sneeze Frequency', clinicalValue: 'Biomechanical and acoustic microphone analyzing nocturnal coughing bouts', frequency: 'Continuous acoustic surveillance', actionableAlert: 'Respiratory infection warning if cough frequency > 6 coughs/hour' },
      { name: 'Premature Ventricular Contraction (PVC) Burden', clinicalValue: 'Quantifies frequency of extra heartbeats originating in the lower ventricles', frequency: 'Hourly tally', actionableAlert: 'Physician notification if PVC burden exceeds 10% of total heartbeats' },
      { name: 'Postural Inclinometer & Bedridden Tracking', clinicalValue: 'Measures torso angle relative to gravity to monitor mobility versus bedbound duration', frequency: 'Continuous 3-axis inclinometer', actionableAlert: 'Pressure ulcer and mobility stagnation prevention alert' },
    ],
  },
  {
    id: 'pulse_oximeter',
    title: 'Continuous Pulse Oximeter Finger / Wrist Trackers',
    subtitle: 'High-Frequency Multi-Wavelength Optical Plethysmography',
    iconName: 'Wind',
    description: 'Specialized optical probes that stream continuous 1-second SpO2, arterial perfusion index, and plethysmographic pulse waveforms.',
    typicalBrands: ['Masimo MightySat Medical', 'Wellue O2Ring Sleep Tracker', 'Nonin WristOx2', 'Contec CMS50F'],
    collectedDataPoints: [
      { name: 'High-Resolution Continuous SpO2', clinicalValue: '1-second optical sampling of oxygenated hemoglobin with medical-grade motion tolerance', frequency: 'Continuous (1 Hz)', actionableAlert: 'Instant silent haptic ring vibration on senior + loud caregiver push alert' },
      { name: 'Perfusion Index (PI %)', clinicalValue: 'Ratio of pulsatile to non-pulsatile blood flow (0.02% to 20%); reflects peripheral vasomotor tone', frequency: 'Continuous 1 Hz', actionableAlert: 'Hypothermia or poor peripheral circulation warning if PI < 1.0%' },
      { name: 'Oxygen Desaturation Index (ODI 4%)', clinicalValue: 'Frequency of blood oxygen dips of 4% or more per hour of sleep; gold standard for sleep apnea severity', frequency: 'Computed hourly', actionableAlert: 'Flagged if ODI > 15 events/hour (moderate to severe sleep apnea)' },
      { name: 'Plethysmographic Waveform Quality Index', clinicalValue: 'Signal integrity metric ensuring readings are not compromised by patient motion or cold hands', frequency: 'Continuous validation', actionableAlert: 'Prompts senior to warm hands or adjust sensor fit if quality drops' },
    ],
  },
  {
    id: 'smart_scale',
    title: 'Smart In-Home Medical Scales & Body Stations',
    subtitle: 'Multi-Frequency Bioelectrical Impedance & Segmental ECG Bar',
    iconName: 'Scale',
    description: 'Full-body scanning stations with retractable handlebar electrodes that measure segmental body composition, vascular age, and nerve health.',
    typicalBrands: ['Withings Body Scan', 'InBody Dial H30', 'Omron Body Composition Monitor', 'Tanita InnerScan'],
    collectedDataPoints: [
      { name: 'Total Weight & Rapid Fluid Shifts', clinicalValue: 'Daily weight trending; sudden weight gain (>2-3 lbs in 24 hrs) indicates acute cardiac fluid retention', frequency: 'Daily morning weigh-in', actionableAlert: 'Congestive heart failure alert on rapid fluid weight spike' },
      { name: 'Pulse Wave Velocity (PWV m/s)', clinicalValue: 'Speed of the arterial pressure wave traveling through the aorta; clinical marker of arterial stiffness', frequency: 'Per weigh-in', actionableAlert: 'Vascular age calculation showing arterial stiffness compared to age peers' },
      { name: '6-Lead Segmental ECG (Leads I, II, III, aVR, aVL, aVF)', clinicalValue: 'Multi-vector electrocardiogram captured through footplates and handlebar electrodes', frequency: 'Per weigh-in (30 seconds)', actionableAlert: 'Arrhythmia and conduction defect screening' },
      { name: 'Sudomotor Electrochemical Skin Conductance (ESC)', clinicalValue: 'Measures sweat gland responsiveness in the soles of feet to detect autonomic peripheral neuropathy', frequency: 'Per weigh-in', actionableAlert: 'Diabetic peripheral neuropathy progression alert' },
      { name: 'Extracellular to Intracellular Water Ratio', clinicalValue: 'Detects fluid accumulation in the extracellular space before visible leg/ankle edema appears', frequency: 'Per weigh-in', actionableAlert: 'Early fluid overload notification to caregiver and nephrologist' },
    ],
  },
  {
    id: 'pendant_insole',
    title: 'Medical Alert Pendants, Badges & Smart Insoles',
    subtitle: 'Kinematic Impact Sensors, Dynamic Foot Pressure & E911 GPS',
    iconName: 'ShieldAlert',
    description: 'Wearable safety pendants, smart orthopedic insoles, and belt badges equipped with barometric fall physics sensors, GPS beaconing, and SOS voice.',
    typicalBrands: ['Medical Guardian MGMini', 'Philips Lifeline CarePoint', 'FeetMe Smart Insoles', 'Sensoria Health Sensor Sock'],
    collectedDataPoints: [
      { name: 'Barometric Altimeter Descent Rate', clinicalValue: 'High-frequency barometric pressure sensor detecting sudden rapid vertical elevation drop (>1.2 meters)', frequency: 'Continuous 10Hz sampling', actionableAlert: 'Pre-impact fall physics trigger initiating emergency confirmation' },
      { name: 'Impact Shock Force Vector (G-force)', clinicalValue: 'Measures multi-axis deceleration magnitude on impact; distinguishes gentle sitting from hard falls', frequency: '100Hz trigger', actionableAlert: 'Traumatic fall confirmation if shock vector exceeds 4.5G' },
      { name: 'Post-Impact Immobility Timer', clinicalValue: 'Watches for absence of voluntary restorative motion following an impact shock', frequency: 'Immediate 15-second observation', actionableAlert: 'Unconscious/incapacitated patient escalation to E911 dispatch' },
      { name: 'Dynamic Plantar Pressure Distribution', clinicalValue: 'Insole pressure grid measuring heel-to-toe load transfer and left/right balance asymmetry', frequency: 'Continuous during walking', actionableAlert: 'Early warning of antalgic limp, joint inflammation, or stroke hemiparesis' },
      { name: 'Freeze-of-Gait (FOG) & Parkinsonian Shuffling', clinicalValue: 'Detects high-frequency tremulous foot vibration and sudden gait hesitation', frequency: 'Continuous walking analysis', actionableAlert: 'Caregiver notification of gait freezing episode' },
      { name: 'Dual-Band GNSS / GPS & WiFi Triangulation', clinicalValue: 'Pins senior location to within 3 meters both indoors and outdoors for emergency response', frequency: 'On-demand & on alert trigger', actionableAlert: 'Dispatches exact coordinates and nearest PSAP relay to EMS' },
    ],
  },
];

export const INITIAL_CONTACTS: EmergencyContact[] = [
  {
    id: 'contact_1',
    name: 'David Miller',
    relation: 'Son (Primary Caregiver / Healthcare Proxy)',
    phone: '+1 (555) 234-8901',
    email: 'david.miller@example.com',
    priorityOrder: 1,
    notifyOnWarning: true,
    notifyOnCritical: true,
    receiveAIVoiceCall: true,
  },
  {
    id: 'contact_2',
    name: 'Sarah Miller Chen',
    relation: 'Daughter (Secondary Caregiver)',
    phone: '+1 (555) 890-1234',
    email: 'sarah.m.chen@example.com',
    priorityOrder: 2,
    notifyOnWarning: false,
    notifyOnCritical: true,
    receiveAIVoiceCall: true,
  },
  {
    id: 'contact_3',
    name: 'Dr. Evelyn Vance, MD',
    relation: 'Attending Cardiologist',
    phone: '+1 (555) 441-0982',
    email: 'clinic.vance@medicare-center.org',
    priorityOrder: 3,
    notifyOnWarning: false,
    notifyOnCritical: true,
    receiveAIVoiceCall: false,
  },
  {
    id: 'contact_4',
    name: 'Regional EMS 911 / Medical Relay',
    relation: 'Municipal First Responders',
    phone: '911 (E911 Digital Dispatch)',
    email: 'dispatch@sangamon-ems.gov',
    priorityOrder: 4,
    notifyOnWarning: false,
    notifyOnCritical: true,
    receiveAIVoiceCall: true,
  },
];

export const INITIAL_CALL_LOGS: AIVoiceCallLog[] = [
  {
    id: 'call_1092',
    timestamp: 'Today at 08:15 AM',
    recipientName: 'Eleanor Miller (Senior)',
    recipientPhone: '+1 (555) 321-7788',
    triggerReason: 'Heart Rate Spike (128 BPM for 4 consecutive minutes)',
    durationSeconds: 48,
    callStatus: 'completed',
    patientResponded: true,
    patientSentiment: 'calm',
    transcription:
      'KINOTE AI: "Hello Eleanor, Kinote detected an elevated pulse of 128 BPM. Are you resting comfortably?" — Eleanor: "Yes, I just carried laundry upstairs, I sat down and took a sip of water." — KINOTE AI: "Pulse is already declining to 102 BPM. Notifying your son David that you are resting safely."',
    dispatchDispatched: false,
    stageReached: 'patient_voice_check',
  },
  {
    id: 'call_1084',
    timestamp: 'Yesterday at 3:30 PM',
    recipientName: 'David Miller (Caregiver)',
    recipientPhone: '+1 (555) 234-8901',
    triggerReason: 'Automated 24-Hour Family Wellness Intelligence Briefing',
    durationSeconds: 35,
    callStatus: 'completed',
    patientResponded: true,
    patientSentiment: 'calm',
    transcription:
      'KINOTE AI: "Good afternoon David. Eleanor’s vitals remained nominal over the last 24 hours. Blood pressure was steady at 122/78 mmHg, SpO2 averaged 98.2%, and her Omron BP cuff battery is at 74%."',
    dispatchDispatched: false,
    stageReached: 'caregiver_escalated',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud_9104',
    timestamp: '2026-09-25 13:20:11 UTC',
    actor: 'david.miller@example.com',
    actorRole: 'family_caregiver',
    action: 'DISPATCH_LOCATION_SWITCHED',
    resource: 'patient.location.preference',
    details: 'Active dispatch rule set to "Primary Residence - Oakwood Home" (Certified Central Relay)',
    severity: 'INFO',
    ipAddress: '198.51.100.42',
    sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'aud_9103',
    timestamp: '2026-09-25 12:45:10 UTC',
    actor: 'system.engine',
    actorRole: 'system_admin',
    action: 'Q1_VOICE_TRIAGE_POLICY_APPLIED',
    resource: 'dispatch.triage_sequence',
    details: 'Cascading triage: Option A (Patient first) -> Option C (Caregiver) -> Option B (3-way conference/EMS)',
    severity: 'INFO',
    ipAddress: '10.0.4.12',
    sha256Hash: 'a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e',
  },
  {
    id: 'aud_9102',
    timestamp: '2026-09-25 11:20:04 UTC',
    actor: 'compliance.officer@kinote.health',
    actorRole: 'compliance_officer',
    action: 'TRI_REGION_COMPLIANCE_AUDIT',
    resource: 'security.hipaa_gdpr_dpdp',
    details: 'Verified HIPAA BAA, GDPR Art. 9 pseudonymization, and India DPDP 2023 revocable consent tokens',
    severity: 'AUDIT',
    ipAddress: '192.0.2.78',
    sha256Hash: 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
  },
  {
    id: 'aud_9101',
    timestamp: '2026-09-24 16:30:19 UTC',
    actor: 'dr.vance@medicare-center.org',
    actorRole: 'attending_physician',
    action: 'CLINICAL_EXPORT',
    resource: 'patient.eleanor_miller.vitals_history',
    details: 'Exported continuous ECG and blood pressure trend report with SHA-256 digital signature',
    severity: 'INFO',
    ipAddress: '198.51.100.119',
    sha256Hash: '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae',
  },
];

export const INITIAL_AI_CHAT_MESSAGES: AIChatMessage[] = [
  {
    id: 'msg_1',
    sender: 'assistant',
    timestamp: 'Today at 09:00 AM',
    content:
      'Hello David! I am Kinote Family Health Intelligence. I continuously monitor Eleanor’s connected wearables (Apple Watch, Omron Cuff, and Oura Ring). All vitals are currently steady. Ask me for a daily summary, device diagnostics, or anomaly analysis anytime.',
    category: 'daily_summary',
    actionableInsights: [
      'Heart Rate resting average: 71 BPM (within target)',
      'Blood Pressure: 122/78 mmHg (optimal)',
      'Wearable uptime: 99.8% across 3 active devices',
    ],
  },
];

export const HISTORICAL_7_DAY_VITALS: HistoricalVitalDay[] = [
  {
    date: '2026-09-19',
    dayLabel: 'Sat',
    formattedDate: 'Sep 19',
    avgHeartRate: 70,
    minHeartRate: 58,
    maxHeartRate: 88,
    restingHeartRate: 64,
    avgSpo2: 98,
    minSpo2: 96,
    maxSpo2: 99,
    systolicBp: 120,
    diastolicBp: 76,
    glucoseAvg: 102,
    status: 'optimal',
    notes: 'Normal morning garden walk, stable daytime recovery',
    sourceDevice: 'Apple Watch Series 10 + Masimo',
  },
  {
    date: '2026-09-20',
    dayLabel: 'Sun',
    formattedDate: 'Sep 20',
    avgHeartRate: 73,
    minHeartRate: 60,
    maxHeartRate: 92,
    restingHeartRate: 66,
    avgSpo2: 97,
    minSpo2: 95,
    maxSpo2: 99,
    systolicBp: 124,
    diastolicBp: 78,
    glucoseAvg: 108,
    status: 'optimal',
    notes: 'Mild afternoon brisk walk with family, sinus rhythm maintained',
    sourceDevice: 'Apple Watch Series 10 + Oura Ring',
  },
  {
    date: '2026-09-21',
    dayLabel: 'Mon',
    formattedDate: 'Sep 21',
    avgHeartRate: 76,
    minHeartRate: 62,
    maxHeartRate: 99,
    restingHeartRate: 68,
    avgSpo2: 97,
    minSpo2: 94,
    maxSpo2: 98,
    systolicBp: 126,
    diastolicBp: 80,
    glucoseAvg: 112,
    status: 'optimal',
    notes: 'Slight evening fatigue after clinic visit, SpO2 stable',
    sourceDevice: 'Apple Watch Series 10 + BioButton',
  },
  {
    date: '2026-09-22',
    dayLabel: 'Tue',
    formattedDate: 'Sep 22',
    avgHeartRate: 69,
    minHeartRate: 56,
    maxHeartRate: 86,
    restingHeartRate: 63,
    avgSpo2: 98,
    minSpo2: 96,
    maxSpo2: 99,
    systolicBp: 119,
    diastolicBp: 75,
    glucoseAvg: 99,
    status: 'optimal',
    notes: 'Optimal rest day, excellent nocturnal HRV rebound',
    sourceDevice: 'Apple Watch Series 10 + Oura Ring',
  },
  {
    date: '2026-09-23',
    dayLabel: 'Wed',
    formattedDate: 'Sep 23',
    avgHeartRate: 71,
    minHeartRate: 59,
    maxHeartRate: 91,
    restingHeartRate: 65,
    avgSpo2: 98,
    minSpo2: 95,
    maxSpo2: 100,
    systolicBp: 121,
    diastolicBp: 77,
    glucoseAvg: 105,
    status: 'optimal',
    notes: 'Morning physical therapy session, heart rate normalized within 4 mins',
    sourceDevice: 'Apple Watch Series 10 + Masimo',
  },
  {
    date: '2026-09-24',
    dayLabel: 'Thu',
    formattedDate: 'Sep 24',
    avgHeartRate: 74,
    minHeartRate: 61,
    maxHeartRate: 94,
    restingHeartRate: 67,
    avgSpo2: 97,
    minSpo2: 95,
    maxSpo2: 99,
    systolicBp: 123,
    diastolicBp: 79,
    glucoseAvg: 106,
    status: 'optimal',
    notes: 'Consistent daytime hydration, normal sleep staging and steady recovery',
    sourceDevice: 'Apple Watch Series 10 + Dexcom G7',
  },
  {
    date: '2026-09-25',
    dayLabel: 'Today',
    formattedDate: 'Sep 25',
    avgHeartRate: 72,
    minHeartRate: 60,
    maxHeartRate: 95,
    restingHeartRate: 68,
    avgSpo2: 98,
    minSpo2: 96,
    maxSpo2: 99,
    systolicBp: 122,
    diastolicBp: 78,
    glucoseAvg: 104,
    status: 'optimal',
    notes: 'Real-time telemetry streaming from connected wearable quorum',
    sourceDevice: 'Apple Watch Series 10 + Masimo MightySat + Oura',
  },
];

export const BASE_INTRADAY_READINGS: HistoricalIntradayReading[] = [
  // Day 1 - Sat
  { id: 'intra_1', timestamp: '2026-09-19T08:00:00', dayLabel: 'Sat', timeLabel: '08:00 AM', period: 'morning', heartRate: 64, spo2: 98, activityContext: 'Waking & morning tea', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_2', timestamp: '2026-09-19T12:30:00', dayLabel: 'Sat', timeLabel: '12:30 PM', period: 'afternoon', heartRate: 78, spo2: 98, activityContext: 'Post-lunch walk in backyard', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_3', timestamp: '2026-09-19T17:30:00', dayLabel: 'Sat', timeLabel: '05:30 PM', period: 'evening', heartRate: 72, spo2: 97, activityContext: 'Relaxing reading book', sensorSource: 'Oura Ring Gen 3' },
  { id: 'intra_4', timestamp: '2026-09-19T22:30:00', dayLabel: 'Sat', timeLabel: '10:30 PM', period: 'night', heartRate: 61, spo2: 98, activityContext: 'Sleep onset (Deep phase)', sensorSource: 'Oura Ring Gen 3' },

  // Day 2 - Sun
  { id: 'intra_5', timestamp: '2026-09-20T08:00:00', dayLabel: 'Sun', timeLabel: '08:00 AM', period: 'morning', heartRate: 66, spo2: 97, activityContext: 'Morning stretch routine', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_6', timestamp: '2026-09-20T12:30:00', dayLabel: 'Sun', timeLabel: '12:30 PM', period: 'afternoon', heartRate: 84, spo2: 97, activityContext: 'Family lunch visit', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_7', timestamp: '2026-09-20T17:30:00', dayLabel: 'Sun', timeLabel: '05:30 PM', period: 'evening', heartRate: 74, spo2: 98, activityContext: 'Evening sitting on patio', sensorSource: 'Masimo MightySat' },
  { id: 'intra_8', timestamp: '2026-09-20T22:30:00', dayLabel: 'Sun', timeLabel: '10:30 PM', period: 'night', heartRate: 62, spo2: 98, activityContext: 'Nocturnal restorative sleep', sensorSource: 'Oura Ring Gen 3' },

  // Day 3 - Mon
  { id: 'intra_9', timestamp: '2026-09-21T08:00:00', dayLabel: 'Mon', timeLabel: '08:00 AM', period: 'morning', heartRate: 68, spo2: 98, activityContext: 'Breakfast & medication check', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_10', timestamp: '2026-09-21T12:30:00', dayLabel: 'Mon', timeLabel: '12:30 PM', period: 'afternoon', heartRate: 88, spo2: 96, activityContext: 'Return transit from clinic', sensorSource: 'BioButton Medical' },
  { id: 'intra_11', timestamp: '2026-09-21T17:30:00', dayLabel: 'Mon', timeLabel: '05:30 PM', period: 'evening', heartRate: 77, spo2: 97, activityContext: 'Watching television', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_12', timestamp: '2026-09-21T22:30:00', dayLabel: 'Mon', timeLabel: '10:30 PM', period: 'night', heartRate: 64, spo2: 97, activityContext: 'Sleep (REM cycle)', sensorSource: 'Oura Ring Gen 3' },

  // Day 4 - Tue
  { id: 'intra_13', timestamp: '2026-09-22T08:00:00', dayLabel: 'Tue', timeLabel: '08:00 AM', period: 'morning', heartRate: 63, spo2: 99, activityContext: 'Waking refreshed', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_14', timestamp: '2026-09-22T12:30:00', dayLabel: 'Tue', timeLabel: '12:30 PM', period: 'afternoon', heartRate: 75, spo2: 98, activityContext: 'Light indoor tidying', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_15', timestamp: '2026-09-22T17:30:00', dayLabel: 'Tue', timeLabel: '05:30 PM', period: 'evening', heartRate: 70, spo2: 98, activityContext: 'Phone call with daughter', sensorSource: 'Oura Ring Gen 3' },
  { id: 'intra_16', timestamp: '2026-09-22T22:30:00', dayLabel: 'Tue', timeLabel: '10:30 PM', period: 'night', heartRate: 59, spo2: 99, activityContext: 'Nocturnal deep sleep dip', sensorSource: 'Oura Ring Gen 3' },

  // Day 5 - Wed
  { id: 'intra_17', timestamp: '2026-09-23T08:00:00', dayLabel: 'Wed', timeLabel: '08:00 AM', period: 'morning', heartRate: 65, spo2: 98, activityContext: 'Pre-PT session baseline', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_18', timestamp: '2026-09-23T12:30:00', dayLabel: 'Wed', timeLabel: '12:30 PM', period: 'afternoon', heartRate: 86, spo2: 97, activityContext: 'Physical therapy exercises', sensorSource: 'Masimo MightySat' },
  { id: 'intra_19', timestamp: '2026-09-23T17:30:00', dayLabel: 'Wed', timeLabel: '05:30 PM', period: 'evening', heartRate: 72, spo2: 98, activityContext: 'Post-PT hydration rest', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_20', timestamp: '2026-09-23T22:30:00', dayLabel: 'Wed', timeLabel: '10:30 PM', period: 'night', heartRate: 61, spo2: 99, activityContext: 'Asleep (Slow-wave sleep)', sensorSource: 'Oura Ring Gen 3' },

  // Day 6 - Thu
  { id: 'intra_21', timestamp: '2026-09-24T08:00:00', dayLabel: 'Thu', timeLabel: '08:00 AM', period: 'morning', heartRate: 67, spo2: 98, activityContext: 'Morning breakfast & coffee', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_22', timestamp: '2026-09-24T12:30:00', dayLabel: 'Thu', timeLabel: '12:30 PM', period: 'afternoon', heartRate: 79, spo2: 97, activityContext: 'Short corridor walk', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_23', timestamp: '2026-09-24T17:30:00', dayLabel: 'Thu', timeLabel: '05:30 PM', period: 'evening', heartRate: 73, spo2: 98, activityContext: 'Dinner with neighbor', sensorSource: 'Dexcom G7' },
  { id: 'intra_24', timestamp: '2026-09-24T22:30:00', dayLabel: 'Thu', timeLabel: '10:30 PM', period: 'night', heartRate: 62, spo2: 98, activityContext: 'Normal nocturnal restorative dip', sensorSource: 'Oura Ring Gen 3' },

  // Day 7 - Today (Sep 25)
  { id: 'intra_25', timestamp: '2026-09-25T08:00:00', dayLabel: 'Today', timeLabel: '08:00 AM', period: 'morning', heartRate: 68, spo2: 98, activityContext: 'Morning wake-up & vitals check', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_26', timestamp: '2026-09-25T11:00:00', dayLabel: 'Today', timeLabel: '11:00 AM', period: 'morning', heartRate: 75, spo2: 98, activityContext: 'Living room mobility exercise', sensorSource: 'Apple Watch Series 10' },
  { id: 'intra_27', timestamp: '2026-09-25T13:30:00', dayLabel: 'Today', timeLabel: '01:30 PM', period: 'afternoon', heartRate: 72, spo2: 98, activityContext: 'Live telemetry stream', sensorSource: 'Masimo MightySat + Watch' },
];

export function getAugmentedHistoricalVitals(
  currentVitals: VitalsReading,
  thresholds: MetricThresholds
): {
  daily: HistoricalVitalDay[];
  intraday: HistoricalIntradayReading[];
  avg7DayHr: number;
  avg7DaySpo2: number;
  min7DayHr: number;
  max7DayHr: number;
  timeInRangeSpo2Percent: number;
} {
  // Clone daily data and update "Today" with live reading
  const daily = HISTORICAL_7_DAY_VITALS.map((d) => {
    if (d.dayLabel === 'Today') {
      const liveHr = currentVitals.heartRate;
      const liveSpo2 = currentVitals.spo2;
      const isWarn = liveHr > thresholds.heartRate.maxWarn || liveHr < thresholds.heartRate.minWarn || liveSpo2 < thresholds.spo2.minWarn;
      const isCrit = liveHr > thresholds.heartRate.maxCritical || liveHr < thresholds.heartRate.minCritical || liveSpo2 < thresholds.spo2.minCritical;
      
      return {
        ...d,
        avgHeartRate: liveHr,
        maxHeartRate: Math.max(d.maxHeartRate, liveHr),
        minHeartRate: Math.min(d.minHeartRate, liveHr),
        avgSpo2: liveSpo2,
        minSpo2: Math.min(d.minSpo2, liveSpo2),
        systolicBp: currentVitals.bloodPressureSystolic,
        diastolicBp: currentVitals.bloodPressureDiastolic,
        glucoseAvg: currentVitals.glucose || d.glucoseAvg,
        status: isCrit ? ('critical' as const) : isWarn ? ('warning' as const) : ('optimal' as const),
        notes: isCrit 
          ? 'CRITICAL ALERT: Threshold breach detected in live wearable telemetry!' 
          : isWarn 
          ? 'WARNING: Live biometrics approaching or breaching warning threshold' 
          : 'Live biometrics nominal and within therapeutic target range',
      };
    }
    return d;
  });

  // Also include the latest live point in intraday readings
  const intraday = [
    ...BASE_INTRADAY_READINGS,
    {
      id: 'intra_live',
      timestamp: currentVitals.timestamp,
      dayLabel: 'Today',
      timeLabel: 'Live Now',
      period: 'afternoon' as const,
      heartRate: currentVitals.heartRate,
      spo2: currentVitals.spo2,
      activityContext: currentVitals.fallDetected ? 'Fall impact event!' : 'Continuous wearable telemetry stream',
      sensorSource: 'Watch + Masimo Quorum',
      isSimulatedToday: true,
    },
  ];

  const totalHr = daily.reduce((acc, curr) => acc + curr.avgHeartRate, 0);
  const totalSpo2 = daily.reduce((acc, curr) => acc + curr.avgSpo2, 0);
  const min7DayHr = Math.min(...daily.map((d) => d.minHeartRate));
  const max7DayHr = Math.max(...daily.map((d) => d.maxHeartRate));
  const optimalSpo2Days = daily.filter((d) => d.avgSpo2 >= 95).length;

  return {
    daily,
    intraday,
    avg7DayHr: Math.round(totalHr / daily.length),
    avg7DaySpo2: Number((totalSpo2 / daily.length).toFixed(1)),
    min7DayHr,
    max7DayHr,
    timeInRangeSpo2Percent: Math.round((optimalSpo2Days / daily.length) * 100),
  };
}

export const INITIAL_MEDICATIONS: MedicationItem[] = [
  {
    id: 'med-lisinopril',
    name: 'Lisinopril',
    genericName: 'Lisinopril (Zestril)',
    dosage: '10 mg',
    form: 'tablet',
    frequency: 'once_daily',
    timingCategory: 'morning',
    scheduledTimes: ['08:00 AM'],
    prescribedFor: 'Essential Hypertension & Renal Hemodynamics',
    prescribingDoctor: 'Dr. Aris Thorne (Cardiology)',
    rxNumber: 'RX-99281-ATH',
    refillRemainingDays: 24,
    pillsRemaining: 48,
    instructions: 'Take 1 tablet every morning with 8oz water. Monitor for orthostatic dizziness.',
    colorTheme: 'rose',
    vitalMetricCorrelation: 'blood_pressure',
    createdAt: '2026-08-01',
    reminders: {
      enabled: true,
      reminderTimes: ['08:00 AM'],
      notificationChannels: {
        pushNotification: true,
        smsAlert: true,
        aiVoiceCallIfMissed: true,
        seniorSafeModeChime: true,
      },
      gracePeriodMinutes: 45,
    },
  },
  {
    id: 'med-metformin',
    name: 'Metformin HCl ER',
    genericName: 'Glucophage XR',
    dosage: '500 mg',
    form: 'tablet',
    frequency: 'twice_daily',
    timingCategory: 'with_meals',
    scheduledTimes: ['08:30 AM', '07:00 PM'],
    prescribedFor: 'Type 2 Glycemic Homeostasis (Dexcom CGM target: 70–140 mg/dL)',
    prescribingDoctor: 'Dr. Aris Thorne (Cardiology / Endocrinology)',
    rxNumber: 'RX-88120-MET',
    refillRemainingDays: 18,
    pillsRemaining: 36,
    instructions: 'Take with breakfast and dinner. Do not crush or chew extended-release formulation.',
    colorTheme: 'teal',
    vitalMetricCorrelation: 'glucose',
    createdAt: '2026-08-01',
    reminders: {
      enabled: true,
      reminderTimes: ['08:30 AM', '07:00 PM'],
      notificationChannels: {
        pushNotification: true,
        smsAlert: false,
        aiVoiceCallIfMissed: false,
        seniorSafeModeChime: true,
      },
      gracePeriodMinutes: 60,
    },
  },
  {
    id: 'med-atorvastatin',
    name: 'Atorvastatin Calcium',
    genericName: 'Lipitor',
    dosage: '20 mg',
    form: 'tablet',
    frequency: 'once_daily',
    timingCategory: 'bedtime',
    scheduledTimes: ['09:30 PM'],
    prescribedFor: 'Hyperlipidemia & Arterial Endothelial Protection',
    prescribingDoctor: 'Dr. Aris Thorne (Cardiology)',
    rxNumber: 'RX-77341-LIP',
    refillRemainingDays: 32,
    pillsRemaining: 32,
    instructions: 'Take 1 tablet at bedtime. Consistent nighttime timing optimizes HMG-CoA reductase inhibition.',
    colorTheme: 'indigo',
    vitalMetricCorrelation: 'heart_rate',
    createdAt: '2026-08-10',
    reminders: {
      enabled: true,
      reminderTimes: ['09:30 PM'],
      notificationChannels: {
        pushNotification: true,
        smsAlert: true,
        aiVoiceCallIfMissed: false,
        seniorSafeModeChime: true,
      },
      gracePeriodMinutes: 60,
    },
  },
  {
    id: 'med-coq10',
    name: 'CoQ10 (Ubiquinol)',
    genericName: 'Coenzyme Q10 Active Form',
    dosage: '100 mg',
    form: 'capsule',
    frequency: 'once_daily',
    timingCategory: 'morning',
    scheduledTimes: ['08:30 AM'],
    prescribedFor: 'Mitochondrial Bioenergetics & Statin Co-therapy Support',
    prescribingDoctor: 'Dr. Aris Thorne (Physician Recommended)',
    rxNumber: 'OTC-55219-COQ',
    refillRemainingDays: 45,
    pillsRemaining: 45,
    instructions: 'Take with morning meal containing healthy fats for enhanced intestinal absorption.',
    colorTheme: 'amber',
    vitalMetricCorrelation: 'heart_rate',
    createdAt: '2026-08-15',
    reminders: {
      enabled: true,
      reminderTimes: ['08:30 AM'],
      notificationChannels: {
        pushNotification: true,
        smsAlert: false,
        aiVoiceCallIfMissed: false,
        seniorSafeModeChime: false,
      },
      gracePeriodMinutes: 90,
    },
  },
];

export const INITIAL_DOSE_LOGS: MedicationDoseLog[] = [
  // Today: Sep 25, 2026
  {
    id: 'dose-today-1',
    medicationId: 'med-lisinopril',
    medicationName: 'Lisinopril',
    dosage: '10 mg',
    scheduledTime: '08:00 AM',
    scheduledDate: '2026-09-25',
    status: 'taken',
    loggedAt: '08:02 AM',
    loggedBy: 'patient',
    notes: 'Confirmed by Eleanor on Senior SafeMode screen.',
  },
  {
    id: 'dose-today-2',
    medicationId: 'med-metformin',
    medicationName: 'Metformin HCl ER',
    dosage: '500 mg',
    scheduledTime: '08:30 AM',
    scheduledDate: '2026-09-25',
    status: 'taken',
    loggedAt: '08:34 AM',
    loggedBy: 'patient',
    notes: 'Taken with morning oatmeal.',
  },
  {
    id: 'dose-today-3',
    medicationId: 'med-coq10',
    medicationName: 'CoQ10 (Ubiquinol)',
    dosage: '100 mg',
    scheduledTime: '08:30 AM',
    scheduledDate: '2026-09-25',
    status: 'taken',
    loggedAt: '08:35 AM',
    loggedBy: 'caregiver',
    notes: 'Verified by David Miller during morning check-in.',
  },
  {
    id: 'dose-today-4',
    medicationId: 'med-metformin',
    medicationName: 'Metformin HCl ER',
    dosage: '500 mg',
    scheduledTime: '07:00 PM',
    scheduledDate: '2026-09-25',
    status: 'upcoming',
  },
  {
    id: 'dose-today-5',
    medicationId: 'med-atorvastatin',
    medicationName: 'Atorvastatin Calcium',
    dosage: '20 mg',
    scheduledTime: '09:30 PM',
    scheduledDate: '2026-09-25',
    status: 'upcoming',
  },

  // Yesterday: Sep 24, 2026
  { id: 'dose-sep24-1', medicationId: 'med-lisinopril', medicationName: 'Lisinopril', dosage: '10 mg', scheduledTime: '08:00 AM', scheduledDate: '2026-09-24', status: 'taken', loggedAt: '08:01 AM', loggedBy: 'patient' },
  { id: 'dose-sep24-2', medicationId: 'med-metformin', medicationName: 'Metformin HCl ER', dosage: '500 mg', scheduledTime: '08:30 AM', scheduledDate: '2026-09-24', status: 'taken', loggedAt: '08:32 AM', loggedBy: 'patient' },
  { id: 'dose-sep24-3', medicationId: 'med-coq10', medicationName: 'CoQ10 (Ubiquinol)', dosage: '100 mg', scheduledTime: '08:30 AM', scheduledDate: '2026-09-24', status: 'taken', loggedAt: '08:33 AM', loggedBy: 'patient' },
  { id: 'dose-sep24-4', medicationId: 'med-metformin', medicationName: 'Metformin HCl ER', dosage: '500 mg', scheduledTime: '07:00 PM', scheduledDate: '2026-09-24', status: 'taken', loggedAt: '07:05 PM', loggedBy: 'patient' },
  { id: 'dose-sep24-5', medicationId: 'med-atorvastatin', medicationName: 'Atorvastatin Calcium', dosage: '20 mg', scheduledTime: '09:30 PM', scheduledDate: '2026-09-24', status: 'taken', loggedAt: '09:28 PM', loggedBy: 'patient' },

  // Sep 23, 2026
  { id: 'dose-sep23-1', medicationId: 'med-lisinopril', medicationName: 'Lisinopril', dosage: '10 mg', scheduledTime: '08:00 AM', scheduledDate: '2026-09-23', status: 'taken', loggedAt: '08:05 AM', loggedBy: 'patient' },
  { id: 'dose-sep23-2', medicationId: 'med-metformin', medicationName: 'Metformin HCl ER', dosage: '500 mg', scheduledTime: '08:30 AM', scheduledDate: '2026-09-23', status: 'taken', loggedAt: '08:30 AM', loggedBy: 'patient' },
  { id: 'dose-sep23-3', medicationId: 'med-coq10', medicationName: 'CoQ10 (Ubiquinol)', dosage: '100 mg', scheduledTime: '08:30 AM', scheduledDate: '2026-09-23', status: 'taken', loggedAt: '08:30 AM', loggedBy: 'patient' },
  { id: 'dose-sep23-4', medicationId: 'med-metformin', medicationName: 'Metformin HCl ER', dosage: '500 mg', scheduledTime: '07:00 PM', scheduledDate: '2026-09-23', status: 'taken', loggedAt: '07:12 PM', loggedBy: 'patient' },
  { id: 'dose-sep23-5', medicationId: 'med-atorvastatin', medicationName: 'Atorvastatin Calcium', dosage: '20 mg', scheduledTime: '09:30 PM', scheduledDate: '2026-09-23', status: 'taken', loggedAt: '09:35 PM', loggedBy: 'patient' },

  // Sep 22, 2026
  { id: 'dose-sep22-1', medicationId: 'med-lisinopril', medicationName: 'Lisinopril', dosage: '10 mg', scheduledTime: '08:00 AM', scheduledDate: '2026-09-22', status: 'taken', loggedAt: '08:00 AM', loggedBy: 'patient' },
  { id: 'dose-sep22-2', medicationId: 'med-metformin', medicationName: 'Metformin HCl ER', dosage: '500 mg', scheduledTime: '08:30 AM', scheduledDate: '2026-09-22', status: 'taken', loggedAt: '08:31 AM', loggedBy: 'patient' },
  { id: 'dose-sep22-3', medicationId: 'med-coq10', medicationName: 'CoQ10 (Ubiquinol)', dosage: '100 mg', scheduledTime: '08:30 AM', scheduledDate: '2026-09-22', status: 'taken', loggedAt: '08:31 AM', loggedBy: 'patient' },
  { id: 'dose-sep22-4', medicationId: 'med-metformin', medicationName: 'Metformin HCl ER', dosage: '500 mg', scheduledTime: '07:00 PM', scheduledDate: '2026-09-22', status: 'taken', loggedAt: '07:02 PM', loggedBy: 'patient' },
  { id: 'dose-sep22-5', medicationId: 'med-atorvastatin', medicationName: 'Atorvastatin Calcium', dosage: '20 mg', scheduledTime: '09:30 PM', scheduledDate: '2026-09-22', status: 'taken', loggedAt: '09:25 PM', loggedBy: 'patient' },

  // Sep 21, 2026 (Clinic visit day - evening dose slightly delayed)
  { id: 'dose-sep21-1', medicationId: 'med-lisinopril', medicationName: 'Lisinopril', dosage: '10 mg', scheduledTime: '08:00 AM', scheduledDate: '2026-09-21', status: 'taken', loggedAt: '08:03 AM', loggedBy: 'patient' },
  { id: 'dose-sep21-2', medicationId: 'med-metformin', medicationName: 'Metformin HCl ER', dosage: '500 mg', scheduledTime: '08:30 AM', scheduledDate: '2026-09-21', status: 'taken', loggedAt: '08:32 AM', loggedBy: 'patient' },
  { id: 'dose-sep21-3', medicationId: 'med-coq10', medicationName: 'CoQ10 (Ubiquinol)', dosage: '100 mg', scheduledTime: '08:30 AM', scheduledDate: '2026-09-21', status: 'taken', loggedAt: '08:32 AM', loggedBy: 'patient' },
  { id: 'dose-sep21-4', medicationId: 'med-metformin', medicationName: 'Metformin HCl ER', dosage: '500 mg', scheduledTime: '07:00 PM', scheduledDate: '2026-09-21', status: 'taken', loggedAt: '07:42 PM', loggedBy: 'caregiver', notes: 'Taken 42 mins late following clinic fatigue.' },
  { id: 'dose-sep21-5', medicationId: 'med-atorvastatin', medicationName: 'Atorvastatin Calcium', dosage: '20 mg', scheduledTime: '09:30 PM', scheduledDate: '2026-09-21', status: 'taken', loggedAt: '09:30 PM', loggedBy: 'patient' },
];

